def normalize_rule_field(obj):
    """
    Normalize rule fields generated by LLM.

    Example:

    Before:
    {
        "source":"游戏vip抽奖",
        "rules":[
            "默认不可转赠"
        ]
    }


    After:
    {
        "source":"游戏vip抽奖",
        "rules":"默认不可转赠"
    }

    """

    if isinstance(obj, dict):

        for key, value in obj.items():

            if key == "rules":

                if isinstance(value, list):

                    obj[key] = "\n".join(
                        value
                    )

            else:

                normalize_rule_field(
                    value
                )


    elif isinstance(obj, list):

        for item in obj:

            normalize_rule_field(
                item
            )


    return obj



def normalize_dimension_array(data):
    """
    Normalize dimension fields.

    Fix:

    Before:
    {
        "source_dimensions":{
            "name":"来源",
            "values":[
                "A",
                "B"
            ]
        }
    }


    After:
    {
        "source_dimensions":[
            {
                "name":"来源",
                "values":[
                    "A",
                    "B"
                ]
            }
        ]
    }

    """

    dimension_fields = [
        "data_dimensions",
        "time_dimensions",
        "source_dimensions"
    ]


    if isinstance(data, dict):

        for key, value in data.items():

            # 只处理 test_design 字段
            if key in dimension_fields:

                if isinstance(value, dict):

                    data[key] = [
                        value
                    ]


            else:

                normalize_dimension_array(
                    value
                )


    elif isinstance(data, list):

        for item in data:

            normalize_dimension_array(
                item
            )


    return data